token: xxxx
webhookURLs:
- "https://discord.com/api/webhooks/xxxxx/xxxxx"
chatChannelIDs:
- 000000000000000000
playingGameName: サーバー稼働中！（{players}/{max}人）

consoleChannel:
  enable: false
  channelId: 000000000000000000
  allowDispatchCommand: true

prefix: "!"
adminRole: ""
updateCheck: true

# Formats
fromDiscordToMinecraftFormat: "§9[Discord] §f<{name}§f> "
fromMinecraftToDiscordName: "{displayName}"
fromDiscordToDiscordName: "{nickName}"

# LunaChat使用時にのみ有効 (Only when using the LunaChat plugin)
japanizeFormat: "__JP__: {japanized}"

# Discordアカウントがリンクされた時にコマンドを実行します
# 以下の値が利用できます
#   {player}    --- プレイヤー名
#   {playerId}  --- プレイヤーUUID
#   {discord}   --- Discordユーザー名
#   {discordId} --- DiscordユーザーID
linkedToConsoleCommand: ""

# この値は変更しないでください！ (Don't change the value!)
configVersion: 4